### ISSUE TITLE
custom build of zeppelin 0.7.2 + spark on dataproc version 1.2.4

### ISSUE THREAD

**Issue by sandys** [GoogleCloudPlatform/dataproc-initialization-actions#133]
hi guys,
we are trying to get a customer build of zeppelin on dataproc version 1.2.4. We have downloaded zeppelin from their releases and set everything correctly. However, we are constantly getting an error:

```
 INFO [2017-08-28 16:02:40,840] ({Thread-0} RemoteInterpreterServer.java[run]:95) - Starting remote interpreter server on port 60775
 INFO [2017-08-28 16:02:41,490] ({pool-1-thread-3} RemoteInterpreterServer.java[createInterpreter]:190) - Instantiate interpreter org.apache.zeppelin.spark.SparkInterpreter
 INFO [2017-08-28 16:02:41,511] ({pool-1-thread-3} RemoteInterpreterServer.java[createInterpreter]:190) - Instantiate interpreter org.apache.zeppelin.spark.SparkSqlInterpreter
 INFO [2017-08-28 16:02:41,516] ({pool-1-thread-3} RemoteInterpreterServer.java[createInterpreter]:190) - Instantiate interpreter org.apache.zeppelin.spark.DepInterpreter
 INFO [2017-08-28 16:02:41,541] ({pool-1-thread-3} RemoteInterpreterServer.java[createInterpreter]:190) - Instantiate interpreter org.apache.zeppelin.spark.PySparkInterpreter
 INFO [2017-08-28 16:02:41,543] ({pool-1-thread-3} RemoteInterpreterServer.java[createInterpreter]:190) - Instantiate interpreter org.apache.zeppelin.spark.SparkRInterpreter
 INFO [2017-08-28 16:02:41,609] ({pool-2-thread-2} SchedulerFactory.java[jobStarted]:131) - Job remoteInterpretJob_1503936161608 started by scheduler interpreter_41495429
 INFO [2017-08-28 16:02:41,612] ({pool-2-thread-2} PySparkInterpreter.java[createPythonScript]:108) - File /tmp/zeppelin_pyspark-8746947718105378480.py created
ERROR [2017-08-28 16:02:42,285] ({pool-2-thread-2} Job.java[run]:188) - Job failed
**java.lang.NoSuchMethodError: scala.reflect.internal.settings.MutableSettings$SettingValue.valueSetByUser()Lscala/Option;**
        at scala.tools.nsc.Global.<init>(Global.scala:334)
        at scala.tools.nsc.interpreter.IMain$$anon$1.<init>(IMain.scala:247)
        at scala.tools.nsc.interpreter.IMain.newCompiler(IMain.scala:247)
        at scala.tools.nsc.interpreter.IMain.<init>(IMain.scala:93)
        at scala.tools.nsc.interpreter.IMain.<init>(IMain.scala:113)
        at scala.tools.nsc.interpreter.ILoop$ILoopInterpreter.<init>(ILoop.scala:108)
        at scala.tools.nsc.interpreter.ILoop.createInterpreter(ILoop.scala:118)
        at org.apache.zeppelin.spark.SparkInterpreter.open(SparkInterpreter.java:783)
        at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
        at org.apache.zeppelin.spark.PySparkInterpreter.getSparkInterpreter(PySparkInterpreter.java:564)
        at org.apache.zeppelin.spark.PySparkInterpreter.createGatewayServerAndStartScript(PySparkInterpreter.java:208)
        at org.apache.zeppelin.spark.PySparkInterpreter.open(PySparkInterpreter.java:162)
        at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
        at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:483)
        at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
        at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:139)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
 INFO [2017-08-28 16:02:42,297] ({pool-2-thread-2} SchedulerFactory.java[jobFinished]:137) - Job remoteInterpretJob_1503936161608 finished by scheduler interpreter_41495429
```

we are very puzzled by this. we tried playing with various version of spark, etc - but it was a no go.
Would really be grateful for any help or direction

**Comment by karth295** [comment]
We have to compile Zeppelin with specific flags and carefully set up its classpath to avoid issues like this. Are you looking for any particular features in 0.7.2 (we currently use 0.7.1), or is this a fork of Zeppelin?

Similarly, do you need a particular version of spark (we currently use 2.2.0), or is this a fork of Spark?

**Comment by karth295** [comment]
Closing this comment since we didn't get a response -- feel free to reopen this issue if you still have questions.
