### ISSUE TITLE
Tez init action breaks Spark

### ISSUE THREAD

**Issue by karth295** [GoogleCloudPlatform/dataproc-initialization-actions#140]
Hive on Tez requires Tez jars to be on the classpath. The Tez init action does correctly configure the classpath for hive, so running hive queries works.

However, Spark depends on Hive, so Tez jars also need to be on Spark's classpath. Here's a snippet of the error I saw when opening a spark shell:

```
$ spark-shell
java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.hive.HiveSessionStateBuilder':
  at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1053)
  at org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:130)
  at org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:130)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:129)
  at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:126)
  at org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:938)
  at org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:938)
  at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
  at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
  at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
  at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
  at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
  at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:938)
  at org.apache.spark.repl.Main$.createSparkSession(Main.scala:97)
  ... 47 elided

...

Caused by: java.lang.reflect.InvocationTargetException: java.lang.NoClassDefFoundError: org/apache/tez/dag/api/SessionNotRunning
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:264)
  ... 78 more

...
```

Environment: Dataproc 1.2.5, single node n1-standard-4.

**Comment by karth295** [comment]
If I change SPARK_DIST_CLASSPATH to be all of `$(hadoop classpath)` (including Tez), Spark is "happy". However, you end up with both a Spark app master and a Tez app master -- and the Tez app master isn't even going to be used! This is particularly unacceptable on small single node clusters, which only allow one app master at a time.

Discussed with @pmkc offline -- the reasonable thing is for the Tez init action to fork `/etc/hive/conf`, and make Spark have its own copy of `hive-site.xml` that is not configured for Tez.
