### ISSUE TITLE
Trying to process a file stored on HDFS from Spark and Zeppelin throws exception 

### ISSUE THREAD

**Issue by skjagini** [GoogleCloudPlatform/dataproc-initialization-actions#372]
Trying to process a file stored on HDFS from Spark and Zeppelin throws exception: `org.apache.hadoop.ipc.RpcException: RPC response exceeds maximum data length`

The file is hardly few KBs, and I am trying to run a basic sample which reads from hdfs and executes  a simple spark transformations and actions 

```scala
val textDS = sc.textFile("hdfs://hadoop123-m:9870/user/hdfs/SampleText.txt")
val words = textDS.flatMap(_.toLowerCase.split(" "))
                                 .filter(_ != " ")
                                 .map(word => (word, 1))
words.count     
```

I have already increased data length as in https://stackoverflow.com/questions/49060244/exception-org-apache-hadoop-ipc-rpcexception-rpc-response-exceeds-maximum-da 
and restarted the node.

I have created the dataproc through: 
```bash
gcloud dataproc clusters create hadoop123 --region us-east1 --subnet default --zone us-east1-d --single-node \
  --master-machine-type n1-standard-2 --master-boot-disk-type pd-ssd --master-boot-disk-size 100 \
  --image-version 1.2 --scopes 'https://www.googleapis.com/auth/cloud-platform' --project iconic-setup-215517 \
  --initialization-actions 'gs://dataproc-initialization-actions/jupyter/jupyter.sh','gs://dataproc-initialization-actions/zookeeper/zookeeper.sh','gs://dataproc-initialization-actions/kafka/kafka.sh','gs://dataproc-initialization-actions/zeppelin/zeppelin.sh'
```

Here is the full exception
```
textDS: org.apache.spark.rdd.RDD[String] = hdfs://hadoop123-m:9870/user/hdfs/SampleText.txt MapPartitionsRDD[79] at textFile at <console>:45
words: org.apache.spark.rdd.RDD[(String, Int)] = MapPartitionsRDD[82] at map at <console>:51
java.io.IOException: Failed on local exception: org.apache.hadoop.ipc.RpcException: RPC response exceeds maximum data length; Host Details : local host is: "myhadoop-m/10.142.0.2"; destination host is: "myhadoop-m":9870;
  at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:785)
  at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1496)
  at org.apache.hadoop.ipc.Client.call(Client.java:1438)
  at org.apache.hadoop.ipc.Client.call(Client.java:1348)
  at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227)
  at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
  at com.sun.proxy.$Proxy12.getFileInfo(Unknown Source)
  at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:796)
  at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:409)
  at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:163)
  at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:155)
  at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
  at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:346)
  at com.sun.proxy.$Proxy13.getFileInfo(Unknown Source)
  at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1649)
  at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1440)
  at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1437)
  at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
  at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1452)
  at org.apache.hadoop.fs.Globber.getFileStatus(Globber.java:64)
  at org.apache.hadoop.fs.Globber.doGlob(Globber.java:269)
  at org.apache.hadoop.fs.Globber.glob(Globber.java:148)
  at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1705)
  at org.apache.hadoop.mapred.LocatedFileStatusFetcher$ProcessInitialInputPathCallable.call(LocatedFileStatusFetcher.java:310)
  at org.apache.hadoop.mapred.LocatedFileStatusFetcher$ProcessInitialInputPathCallable.call(LocatedFileStatusFetcher.java:291)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.ipc.RpcException: RPC response exceeds maximum data length
  at org.apache.hadoop.ipc.Client$IpcStreams.readResponse(Client.java:1811)
  at org.apache.hadoop.ipc.Client$Connection.receiveRpcResponse(Client.java:1166)
  at org.apache.hadoop.ipc.Client$Connection.run(Client.java:1062)
```

**Comment by skjagini** [comment]
It looks like I am passing invalid port number,  apparently no port number is required
sc.textFile("hdfs://hadoop123-m/user/hdfs/SampleText.txt")

in core-site.xml we don't have any port number associated with defaultFS
 <property>
    <name>fs.defaultFS</name>
    <value>hdfs://myhadoop-m</value>
    <description>
      The name of the default file system. A URI whose scheme and authority
      determine the FileSystem implementation. The uri's scheme determines
      the config property (fs.SCHEME.impl) naming the FileSystem
      implementation class. The uri's authority is used to determine the
      host, port, etc. for a filesystem.
    </description>
  </property>
