### ISSUE TITLE
python.conda doesn't seem to function with the Zeppelin action

### ISSUE THREAD

**Issue by bbhoss** [GoogleCloudPlatform/dataproc-initialization-actions#373]
Fresh install, followed the docs to a T. When I create a python interpreter notebook and run 
```
%python.conda install seaborn
```
Gives me this stack trace:
```
java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at org.apache.zeppelin.python.PythonCondaInterpreter.runCommand(PythonCondaInterpreter.java:393)
	at org.apache.zeppelin.python.PythonCondaInterpreter.runCondaCommandForTextOutput(PythonCondaInterpreter.java:179)
	at org.apache.zeppelin.python.PythonCondaInterpreter.runCondaInstall(PythonCondaInterpreter.java:285)
	at org.apache.zeppelin.python.PythonCondaInterpreter.interpret(PythonCondaInterpreter.java:98)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:97)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:498)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
	at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:139)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by karth295** [comment]
Sorry for the late reply -- this is just because Conda isn't installed. You could run the [conda init action](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/conda) to install it.

You could also Dataproc's new [Optional Components](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/optional-components), which are essentially the init actions, but pre-installed.

This is what I used:

```
gcloud dataproc clusters create my-cluster --optional-components ANACONDA,ZEPPELIN --image-version=1.3
```

However, this still doesn't seem to work. `python.conda info` seems fine:

```
     active environment : None
       user config file : /var/lib/zeppelin/.condarc
 populated config files : 
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 2.7.14.final.0
       base environment : /opt/conda/anaconda  (read only)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /opt/conda/anaconda/pkgs
                          /var/lib/zeppelin/.conda/pkgs
       envs directories : /var/lib/zeppelin/.conda/envs
                          /opt/conda/anaconda/envs
               platform : linux-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/2.7.14 Linux/4.9.0-8-amd64 debian/9 glibc/2.24
                UID:GID : 115:993
             netrc file : None
           offline mode : False
```

But then `python.conda install seaborn` doesn't seem to work:

```
java.lang.RuntimeException: Failed to execute `conda install --yes seaborn` exited with 1
	at org.apache.zeppelin.python.PythonCondaInterpreter.runCommand(PythonCondaInterpreter.java:412)
	at org.apache.zeppelin.python.PythonCondaInterpreter.runCondaCommandForTextOutput(PythonCondaInterpreter.java:180)
	at org.apache.zeppelin.python.PythonCondaInterpreter.runCondaInstall(PythonCondaInterpreter.java:286)
	at org.apache.zeppelin.python.PythonCondaInterpreter.interpret(PythonCondaInterpreter.java:99)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:103)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:633)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:188)
	at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:140)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I suspect this is because `conda` is in $PATH for login shells, but not for non-login shells.

Login shell:

```
$ sudo su zeppelin -l -s /bin/bash -c "conda"
usage: conda [-h] [-V] command ...
```

Not login shell:

```
$ sudo su zeppelin -s /bin/bash -c "conda"
bash: conda: command not found
```

**Comment by karth295** [comment]
My suspicion was wrong.

1) `%sh conda info` works just fine
2) `%sh conda install seaborn` hits a permission error (need to be sudo, not Zeppelin)

**Comment by karth295** [comment]
Ah I get it now -- `%python.conda install seaborn` is failing with the same issue -- `OSError(13, 'Permission denied')` since you need to be root to install packages.

**Comment by karth295** [comment]
I was able to get it to work by creating a new conda environment -- which is how you're supposed to use Conda in a multi-user environment:

```
%python.conda create --name my-env
%python.conda activate my-env
%python.conda install seaborn
```

Then this works just fine:

```
%pyspark
import seaborn
```

**Comment by karth295** [comment]
The one thing to note is that this is only installing packages on the cluster's master node. If you're in a multi-node cluster (very likely), you will likely need to install packages on all nodes.

If you're using the conda init action, you can add extra packages like this --metadata 'CONDA_PACKAGES="numpy pandas",PIP_PACKAGES=pandas-gbq'`. If you're using the optional component ANACONDA, you will need to run an initialization action to install packages across the cluster.

**Comment by karth295** [comment]
CC @DanSedov @pmkc  in case you have any additional insights here.
