### ISSUE TITLE
 Hue install process failed

### ISSUE THREAD

**Issue by sundhar010** [GoogleCloudPlatform/dataproc-initialization-actions#395]

**Comment by medb** [comment]
May you try to install Hue without Cloud SQL Proxy to check if problem in compatibility between these init actions or in Hue per se?

**Comment by sundhar010** [comment]
@medb But I need the cluster to access hive metastore and for that, the SQL proxy is needed.

**Comment by medb** [comment]
I understand, this is not a solution, but it will help to pin down the problem.

**Comment by sundhar010** [comment]
I tried installing only Hue and it worked. It got installed.

**Comment by mikaylakonst** [comment]
I was able to reproduce your issue.

Can you try swapping the order of the hue init action and the cloud sql proxy init action so that the hue init action comes first? That seemed to work for me

**Comment by sundhar010** [comment]
@mikaylakonst I tried swapping the order of the init actions the cluster got deployed but got the following error if I try to access the hue web interface.
Error: https://pastebin.com/1WnpagFh 
Thanks

**Comment by daithi-walker** [comment]
I've the same issue. I created the db, user and privs on the cloud sql instance but I dont see how that helps?

Also, when trying to restart the mysql service (on the dataproc server I presume?), I am getting an issue. No idea why...

`sudo systemctl status mysql.service
● mysql.service - LSB: Start and stop the mysql database server daemon
   Loaded: loaded (/etc/init.d/mysql; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-02-06 18:56:12 UTC; 4s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 6690 ExecStart=/etc/init.d/mysql start (code=exited, status=1/FAILURE)

Feb 06 18:55:43 hive-cluster-m mysqld[6942]: 2019-02-06 18:55:43 140035900217536 [Note] Server socket created on IP: '0.0.0.0'.
Feb 06 18:55:43 hive-cluster-m mysqld[6942]: 2019-02-06 18:55:43 140035900217536 [ERROR] Can't start server: Bind on TCP/IP port. Got error: 98: Address already in use
Feb 06 18:55:43 hive-cluster-m mysqld[6942]: 2019-02-06 18:55:43 140035900217536 [ERROR] Do you already have another mysqld server running on port: 3306 ?
Feb 06 18:55:43 hive-cluster-m mysqld[6942]: 2019-02-06 18:55:43 140035900217536 [ERROR] Aborting
Feb 06 18:55:43 hive-cluster-m mysqld[6942]: 
Feb 06 18:56:12 hive-cluster-m mysql[6690]: Starting MariaDB database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
Feb 06 18:56:12 hive-cluster-m systemd[1]: mysql.service: Control process exited, code=exited status=1
Feb 06 18:56:12 hive-cluster-m systemd[1]: Failed to start LSB: Start and stop the mysql database server daemon.
Feb 06 18:56:12 hive-cluster-m systemd[1]: mysql.service: Unit entered failed state.
Feb 06 18:56:12 hive-cluster-m systemd[1]: mysql.service: Failed with result 'exit-code'.
`
And if I try to run the hue script with syncdb or migrate options, I get another error:

`sudo /usr/lib/hue/build/env/bin/hue syncdb --noinput
Traceback (most recent call last):
  File "/usr/lib/hue/build/env/bin/hue", line 14, in <module>
    load_entry_point('desktop', 'console_scripts', 'hue')()
  File "/usr/lib/hue/desktop/core/src/desktop/manage_entry.py", line 216, in entry
    execute_from_command_line(sys.argv)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/hue/desktop/core/src/desktop/settings.py", line 271, in <module>
    conf.initialize(_desktop_conf_modules, _config_dir)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/conf.py", line 598, in initialize
    conf_data = load_confs(_configs_from_dir(config_dir))
  File "/usr/lib/hue/desktop/core/src/desktop/lib/conf.py", line 530, in load_confs
    for in_conf in conf_source:
  File "/usr/lib/hue/desktop/core/src/desktop/lib/conf.py", line 511, in _configs_from_dir
    conf = ConfigObj(os.path.join(conf_dir, filename))
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/configobj-5.0.6-py2.7.egg/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/lib/hue/build/env/lib/python2.7/site-packages/configobj-5.0.6-py2.7.egg/configobj.py", line 1318, in _load
    raise error
configobj.DuplicateError: Duplicate keyword name at line 1906.`


Any ideas?

**Comment by Fahadsaadullahkhan** [comment]
**SOLUTION**
`CREATE DATABASE hue; `
`CREATE USER 'hue'@'localhost' IDENTIFIED BY '<password>';  `
`GRANT ALL PRIVILEGES ON hue.* TO 'hue'@'localhost'; `

Then go to /etc/hue/conf and edit file hue.ini, in that file there are four parameters should be like following:
`host=127.0.0.1`
`port=3306`
`engine=mysql`
`user=hue`
`password=<your_hue_password_in_mysql_instance>`

Kill the process which is running on 0.0.0.0:8888 by following command
`ps -f -u hue | grep -i runspawningserver
`
Give permissions to hue user to create log file in /usr/lib/hue/build/env/bin/logs
`sudo chown hue:hue /usr/lib/hue/build/env/bin/logs`

Then go to /usr/lib/hue/build/env/bin/ directory and run following commands
`sudo ./hue syncdb --noinput`
`sudo ./hue migrate`
If the migration is completed successfully then start hue server by following command
`sudo ./hue runcpserver &`

Now if you'll go to `<yourclustername-m>:8888,` you'll see the hue UI.

**Comment by hugomsm** [comment]
Hello, for anyone having this issue, I've managed to correct this issue and connect Hue with Cloud SQL Proxy. **DON'T** use the Hue init script on init action having Cloud SQL Proxy, **it will fail**. You need to **manually edit the hue.sh** script to change the following lines:

https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/a341516f4912dc15d1baf3c0eb0b33728bcfe277/hue/hue.sh#L153-L170

What I've did:

Changed from: 

mysql -u root -p root-password -e " \
    CREATE DATABASE hue; \
    CREATE USER 'hue'@'localhost' IDENTIFIED BY '${hue_password}'; \
    GRANT ALL PRIVILEGES ON hue.* TO 'hue'@'localhost';" \
    || err "Unable to create database"

To:

mysql -u root -p -e " \
    CREATE DATABASE hue; \
    CREATE USER 'hue'@'%' IDENTIFIED BY '${hue_password}'; \
    GRANT ALL PRIVILEGES ON hue.* TO 'hue'@'%';" \
    || err "Unable to create database"

Then, I manually copied the script to the Dataproc's Master Node, ran the script with "sudo bash hue.sh" inside the Master node of the Dataproc cluster. It will ask for the root password of Cloud SQL, then you input it and press enter. Then, the installation will proceed normally. 

If you already have ran the command before, getting the error, recreate the cluster without the init script. It leaves some mess and if you try to correct the hue.sh file and run again, it will fail (I was getting these errors, and after a clean Dataproc installation, it worked well with the changes that I've mentioned).
