### ISSUE TITLE
Kafka initialization fails GCP

### ISSUE THREAD

**Issue by iJup** [GoogleCloudPlatform/dataproc-initialization-actions#487]
The below Kafka initialization return consequently an error:

<img width="571" alt="Schermafbeelding 2019-03-30 om 11 49 50" src="https://user-images.githubusercontent.com/12045851/55275134-ef743380-52e1-11e9-9544-476649047241.png">

The tail of the log file looks like this:

<img width="682" alt="Schermafbeelding 2019-03-30 om 11 51 36" src="https://user-images.githubusercontent.com/12045851/55275149-39f5b000-52e2-11e9-9d2c-face4ae6e31a.png">

I created a cluster from the command line according to:

```
gcloud dataproc clusters create CLUSTER \
		--bucket BUCKET \
		--properties=^#^spark:spark.jars.packages=graphframes:graphframes:0.5.0-spark2.1-s_2.11,com.databricks:spark-xml_2.11:0.4.1 \
		--subnet default \
		--zone europe-west2-b \
		--master-machine-type n1-standard-2 \
		--master-boot-disk-size 50 \
		--num-workers 2 \
		--worker-machine-type n1-standard-2 \
		--worker-boot-disk-size 50 \
		--image-version 1.3-deb9 \
		--project PROJECT_ID \
		--metadata "run-on-master=true" \
		--initialization-actions 'gs://dataproc-initialization-actions/jupyter/jupyter.sh','gs://dataproc-initialization-actions/zookeeper/zookeeper.sh','gs://dataproc-initialization-actions/kafka/kafka.sh','gs://st446-bucket3/my-actions.sh' 
```

**Comment by functicons** [comment]
I reproduced the problem. I saw Kafka on worker-1 failed to start because it timed out connecting to ZooKeeper. I think it is caused by the jupyter init action, because it only runs on master node, it delayed when ZooKeeper get started; Kafka on worker-1 tried to connect to the ZooKeeper on the master, but ZooKeeper was not up yet and it timed out. I can try to improve the Kafka init action, one option is to connect ZooKeeper of the same node when possible.

$ sudo systemctl status kafka-server

● kafka-server.service - LSB: Kafka Server
   Loaded: loaded (/etc/init.d/kafka-server; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-04-09 17:36:52 UTC; 4min 24s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 25383 ExecStop=/etc/init.d/kafka-server stop (code=exited, status=0/SUCCESS)
  Process: 24857 ExecStart=/etc/init.d/kafka-server start (code=exited, status=0/SUCCESS)
 Main PID: 24871 (code=exited, status=1/FAILURE)

$ cat /var/log/kafka/kafka-server.out

[2019-04-09 17:36:51,899] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
        at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply$mcV$sp(ZooKeeperClient.scala:225)
        at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:221)
        at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:221)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:250)
        at kafka.zookeeper.ZooKeeperClient.kafka$zookeeper$ZooKeeperClient$$waitUntilConnected(ZooKeeperClient.scala:221)
        at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:95)
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1547)
        at kafka.server.KafkaServer.kafka$server$KafkaServer$$createZkClient$1(KafkaServer.scala:348)
        at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:372)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
        at kafka.Kafka$.main(Kafka.scala:75)
        at kafka.Kafka.main(Kafka.scala)
