### ISSUE TITLE
Intitializing Scala interpreter is stuck in the process of initialising..

### ISSUE THREAD

**Issue by ChethanUK** [GoogleCloudPlatform/dataproc-initialization-actions#507]
Hello, I deployed Dataproc Cluster 

```bash
gcloud beta dataproc clusters create presto \
    --optional-components=ANACONDA,JUPYTER,PRESTO \
    --zone europe-north1-b --master-machine-type n1-standard-4 --master-boot-disk-size 500 \
    --num-workers 2 --worker-machine-type n1-standard-4 --worker-boot-disk-size 1000 \
    --num-preemptible-workers 3 --image-version 1.4-debian9 \
    --properties spark:spark.jars.packages=datastax:spark-cassandra-connector:2.4.1-s_2.11 \
    --enable-component-gateway
```

The cluster was deployed successfully, except one warning, which is fine though and status of the cluster is running:
> For PD-Standard, we strongly recommend provisioning 1TB or larger to ensure consistently high I/O performance. See https://cloud.google.com/compute/docs/disks/performance for information on disk I/O performance.

But, when I open Jupyter Component Gateway (Jupyter notebook in Web) and start scale kernel and run any cell with `val a = 10`, Jupyter Kernel will get stuck in `Initializing Scala interpreter ...` 

![Stuck](https://i.imgur.com/7ITSfSF.png)

Even if you wait for 10, 20... minutes it won't get initialized, It's not just this deployment issue, I tried deployment in 3 different zones and tried to restart the kernel many times and initialize the Scala interpreter again. But as always, the initializing perhaps will never get initialized..

**Comment by ostrokach** [comment]
I think this is because by default all the resources in the cluster are allocated to the Flink session, so Scala is hanging when trying to obtain some resources for Spark.

**Comment by ChethanUK** [comment]
There was no flink in cluster

**Comment by karth295** [comment]
I think the cassandra connector dependency is incorrect (looking in jupyter_notebook.log):

```
Ivy Default Cache set to: /root/.ivy2/cache
The jars for the packages stored in: /root/.ivy2/jars
:: loading settings :: url = jar:file:/usr/lib/spark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[D 20:49:35.980 NotebookApp] 200 GET /gateway/default/jupyter/static/base/images/favicon-notebook.ico (127.0.0.1) 1.20ms
datastax#spark-cassandra-connector added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-7cb23334-d1ec-40f1-9956-254a424e5360;1.0
        confs: [default]
[D 20:49:36.634 NotebookApp] 304 GET /gateway/default/jupyter/static/base/images/favicon-busy-1.ico (127.0.0.1) 0.99ms
:: resolution report :: resolve 683ms :: artifacts dl 0ms
        :: modules in use:
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
                module not found: datastax#spark-cassandra-connector;2.4.1-s_2.11

        ==== local-m2-cache: tried

          file:/root/.m2/repository/datastax/spark-cassandra-connector/2.4.1-s_2.11/spark-cassandra-connector-2.4.1-s_2.11.pom

          -- artifact datastax#spark-cassandra-connector;2.4.1-s_2.11!spark-cassandra-connector.jar:

          file:/root/.m2/repository/datastax/spark-cassandra-connector/2.4.1-s_2.11/spark-cassandra-connector-2.4.1-s_2.11.jar

        ==== local-ivy-cache: tried

          /root/.ivy2/local/datastax/spark-cassandra-connector/2.4.1-s_2.11/ivys/ivy.xml

          -- artifact datastax#spark-cassandra-connector;2.4.1-s_2.11!spark-cassandra-connector.jar:

          /root/.ivy2/local/datastax/spark-cassandra-connector/2.4.1-s_2.11/jars/spark-cassandra-connector.jar

        ==== central: tried

          https://repo1.maven.org/maven2/datastax/spark-cassandra-connector/2.4.1-s_2.11/spark-cassandra-connector-2.4.1-s_2.11.pom

          -- artifact datastax#spark-cassandra-connector;2.4.1-s_2.11!spark-cassandra-connector.jar:

          https://repo1.maven.org/maven2/datastax/spark-cassandra-connector/2.4.1-s_2.11/spark-cassandra-connector-2.4.1-s_2.11.jar

        ==== spark-packages: tried

          https://dl.bintray.com/spark-packages/maven/datastax/spark-cassandra-connector/2.4.1-s_2.11/spark-cassandra-connector-2.4.1-s_2.11.pom

          -- artifact datastax#spark-cassandra-connector;2.4.1-s_2.11!spark-cassandra-connector.jar:

          https://dl.bintray.com/spark-packages/maven/datastax/spark-cassandra-connector/2.4.1-s_2.11/spark-cassandra-connector-2.4.1-s_2.11.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: datastax#spark-cassandra-connector;2.4.1-s_2.11: not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: datastax#spark-cassandra-connector;2.4.1-s_2.11: not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1306)
        at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:315)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[MetaKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/opt/conda/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/opt/conda/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/opt/conda/anaconda/lib/python3.6/site-packages/metakernel/_metakernel.py", line 395, in do_execute
    retval = self.do_execute_direct(code)
  File "/opt/conda/anaconda/lib/python3.6/site-packages/spylon_kernel/scala_kernel.py", line 141, in do_execute_direct
    res = self._scalamagic.eval(code.strip(), raw=False)
  File "/opt/conda/anaconda/lib/python3.6/site-packages/spylon_kernel/scala_magic.py", line 157, in eval
    intp = self._get_scala_interpreter()
  File "/opt/conda/anaconda/lib/python3.6/site-packages/spylon_kernel/scala_magic.py", line 46, in _get_scala_interpreter
    self._interp = get_scala_interpreter()
  File "/opt/conda/anaconda/lib/python3.6/site-packages/spylon_kernel/scala_interpreter.py", line 568, in get_scala_interpreter
    scala_intp = initialize_scala_interpreter()
  File "/opt/conda/anaconda/lib/python3.6/site-packages/spylon_kernel/scala_interpreter.py", line 163, in initialize_scala_interpreter
    spark_session, spark_jvm_helpers, spark_jvm_proc = init_spark()
  File "/opt/conda/anaconda/lib/python3.6/site-packages/spylon_kernel/scala_interpreter.py", line 99, in init_spark
    spark_context = conf.spark_context(application_name)
  File "/opt/conda/anaconda/lib/python3.6/site-packages/spylon/spark/launcher.py", line 521, in spark_context
    return pyspark.SparkContext(appName=application_name, conf=spark_conf)
  File "/usr/lib/spark/python/pyspark/context.py", line 133, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/usr/lib/spark/python/pyspark/context.py", line 316, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/usr/lib/spark/python/pyspark/java_gateway.py", line 46, in launch_gateway
    return _launch_gateway(conf)
  File "/usr/lib/spark/python/pyspark/java_gateway.py", line 108, in _launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number
```

**Comment by ChethanUK** [comment]
Now it's `com.datastax.spark:spark-cassandra-connector_2.11:2.4.1`
Thanks for checking!.

**Comment by CateGitau** [comment]
Currently having this issue as well @ChethanUK did you solve it? and How?

**Comment by ChethanUK** [comment]
@CateGitau send your init command.

**Comment by anandgaikwad09** [comment]
Hello @ChethanUK and @CateGitau , how did you solved it?

**Comment by jrtechs** [comment]
I'm having the same issue. Is it an issue with an older version?

**Comment by ChethanUK** [comment]
> I'm having the same issue.

Check your jars? Which Dataproc image are you using?

**Comment by xychen1007** [comment]
Same issue, anyone can come up with some ideas?

**Comment by jmanuelc87** [comment]
I've just updated jupyter lab to version 1.2.6, and installed spylon kernel but it's stuck in the label "Intitializing Scala interpreter ..."

anyone?

**Comment by medb** [comment]
@xychen1007 @jmanuelc87 please, open a new issue(s) instead of posting comments to the existing and closed issue.

Please, include full command that you use to create Dataproc cluster and error/exception that you face.

**Comment by kanna1403** [comment]
Make sure you have a spark installed on your device.
I had a similar issue and realized that spark was not installed. Followed the instructions here and it worked fine 
https://bigdata-madesimple.com/guide-to-install-spark-and-use-pyspark-from-jupyter-in-windows/
